### ISSUE TITLE
Channel list header title display quirk caused by `]` character

### ISSUE THREAD

**Issue by wedebe** [openatv/enigma2#2621] opened 2022-10-24 07:54 UTC
Changing to a channel in a bouquet with a long name, then back to a channel in, eg. Favourites, doesn't clear the previous title fully.

![4097_0_0_0_0_0_0_0_0_0_20221024085327](https://user-images.githubusercontent.com/9741693/197475868-f33495c3-2b7b-4b26-92ca-e6e566f63f78.jpg)

```
#NAME Shoutcast [4097:0:1]
#SERVICE 4097:0:1:0:0:0:0:0:0:0:https%3a//streamssl.chilltrax.com/:Chilltrax
#DESCRIPTION Chilltrax
#SERVICE 4097:0:1:0:0:0:0:0:0:0:https%3a//www.radioking.com/play/consol-tanning:♪ Consol Radio
#DESCRIPTION ♪ Consol Radio
```

**Comment by kiddac** [comment] 2022-10-26 19:41
The problem is not the length, but probably the name of your bouquet 
Why has it got [4097:0:1] in the name?

The code is probably looking for the service type to do some operation. i.e 4097:

**Comment by wedebe** [comment] 2022-10-26 20:28
`:` isn't the issue. This also happens when `_` characters are used instead.

**Comment by wedebe** [comment] 2022-10-26 20:58
I've found the issue - `]` and - somewhat bizarrely - the preceding 4 characters are shown when changing channel from such a bouquet.

```
#NAME Bouquets (TV)
#SERVICE 1:7:1:0:0:0:0:0:0:0:FROM BOUQUET "userbouquet.shoutcast__4097_0_1_.tv" ORDER BY bouquet:Shoutcast _4097_0_1_
#DESCRIPTION abcdefgh]ijklmnop
```

![4097_0_0_0_0_0_0_0_0_0_20221026215550](https://user-images.githubusercontent.com/9741693/198136416-c3b56b7e-cee7-4634-9aff-757533a43e0d.jpg)

**Comment by IanSav** [comment] 2023-05-20 17:18
A proposed fix for ChannelSelection titles has just been committed in https://github.com/openatv/enigma2/pull/2894.  Please test the new code and report if all the title issues are fixed.

**Closed** 2023-05-21 11:04 UTC
