### ISSUE TITLE
Restart Network

### ISSUE THREAD

**Issue by luka838** [openatv/enigma2#1841] opened 2020-09-08 19:05 UTC
Hi every time I try to restat network to change IP 
the ip change but notification message show up I can't remember what say but it never disappear even with if I press exit button or menu from Remote-Ctrl
Edit: I grab photo of the stuck message when restart network
![1599600919623](https://user-images.githubusercontent.com/70975338/92530371-8d389580-f22c-11ea-8100-c37a1c44537e.jpg)

also on unrelated matter I noticed that all 2nd generations of vuplus got openatv 6.5 beta accept for Vusolo SE never got one even Vu Duo2 and Solo2 got one why is that?

**Comment by wedebe** [comment] 2020-09-08 21:51
I've experienced this too, but I'd put it down to my wifi dongle being the cause. I still have older images somewhere that I might try.

**Comment by 4l3x2k** [comment] 2020-09-09 18:31
As far as I know oATV 6.5 Images are build upon request at the oATV Forum for (plugin-) developers or skinner.
This problem may be fixed in 6.5.

**Comment by luka838** [comment] 2020-09-10 10:37
thanks wedebe and 4l3x2k
but if there no openATV 6.5 for my box untill now. how is this will be fixed?

**Comment by 4l3x2k** [comment] 2020-09-10 11:12
I think this will be fixed if version 6.5 is public beta. This depend on core developer resources and infrastructure resources. More money, man power, storage and processing power is required. Last but not least, time.

This is my point of view as I'am not a core developer.

**Comment by nickersk** [comment] 2020-09-10 11:43
are we talking about 6.5 image for vu solo se v2?

**Comment by nickersk** [comment] 2020-09-10 19:28
here is latest 6.5 image for vu solo se/se v2 https://we.tl/t-8Rr7neZyuR

**Comment by luka838** [comment] 2020-09-12 17:55
thank you nickersk
but do I am able to online-update this image or not?
because vusolose's openATV 6.5 page still empty and no image in it.
images.mynonpublic.com/openatv/6.5/index.php?open=vusolose

**Comment by nickersk** [comment] 2020-09-12 18:39
feeds are not yet built since 6.5 is alpha

**Comment by 4l3x2k** [comment] 2020-09-12 20:54
@luka838 
Would be nice if you could check your network issue with 6.5 and report back. close or leave this issue.

**Comment by 4l3x2k** [comment] 2021-08-07 14:25
@luka838 @wedebe 
Does the problem still exist?
If the problem persists, how do you trigger the network restart?
Via the extension menu (blue long) or Settings - System - Network - Network adapter settings?

As 6.5 is EOL please also try with 7.0.

**Comment by wedebe** [comment] 2022-05-05 21:22
No longer an issue in 7.0

**Closed** 2022-05-05 21:26 UTC
