### ISSUE TITLE
Zgemma H.2S and S core update removing linux core binaries

### ISSUE THREAD

**Issue by p17blo** [openatv/enigma2#533] opened 2016-12-08 20:46 UTC
One of the latest software updates specific to Zgemma boxes is removing Linux binaries (cp, mv, find, wget, ls)

**Comment by Schimmelreiter** [comment] 2016-12-08 20:50
You need to reflash. 
Not related to enigma2 but opkg and not fixable, as the broken opkg can't update itself to the fixed one.
We have been delaying this event for 2.5 months now.

**Closed by Schimmelreiter** 2016-12-08 20:50 UTC

**Comment by p17blo** [comment] 2016-12-08 21:02
Reflash then update causes the same issue - Can't claim close on this and state reflash!  There is something in the underlying code that needs fixing

**Comment by Schimmelreiter** [comment] 2016-12-09 00:34
Either way:
It's not an issue in E2, so it's correct to close it here.

And it's quite obvious what causes it:
An old opkg is trying to upgrade busybox.

We are fully aware of what causes it, but the problem is that the fix itself would cause the same problem, the broken opkg can not upgrade itself to a good one.

The only solution **is** a reflash, which will bring the new versions of opkg and busybox.
It might be that ZGemma H.2S wasn't compiled since that change, so just don't do online updates for a day or two and then reflash with a new image (Backup + restore settings will work).

**Comment by Schimmelreiter** [comment] 2016-12-09 00:38
You can see here that the problem in opkg was already fixed in September:
https://github.com/oe-alliance/oe-alliance-core/commit/a5bcce5a69ebd8d4c295d5a1586df1b1dd36ffd8
(See especially bug nr. 3!).

We simply can not bring this change to you except by reflash.
