### ISSUE TITLE
[BUG] Restore wizard (opkg) - `Missing new line character at end of file!`

### ISSUE THREAD

**Issue by wedebe** [openatv/enigma2#2704] opened 2022-12-07 12:58 UTC
Presented with list of backupped plugins, pressing `Install` leads to the following:

```
Installiere Plugins vom Feed..

Fortschritt der Ausfuhrung:

* parse_from_stream_nomalloc: Missing new line character at end of file!
```

[20221207-140303-enigma2-debug.log](https://github.com/openatv/enigma2/files/10176278/20221207-140303-enigma2-debug.log)

**Comment by jbleyel** [comment] 2022-12-09 10:10
Please run this in console:

`opkg upgrade -V4 > /tmp/opkg.log`

and provide the `/tmp/opkg.log`

**Comment by romestylez** [comment] 2022-12-09 11:29
As requested. I did it on two of my receivers but config should be the same.

[opkg.log](https://github.com/openatv/enigma2/files/10194276/opkg.log)
[opkg_2.log](https://github.com/openatv/enigma2/files/10194281/opkg_2.log)

**Comment by jbleyel** [comment] 2022-12-09 18:10
Strange.
The error `parse_from_stream_nomalloc` is not in the logs.

**Comment by jbleyel** [comment] 2022-12-10 09:56
I need the log again if the error occurred.
You may need to find a way to reproduce the error.
And then always call this : `opkg upgrade -V4 > /tmp/opkg.log` to create the log.

**Comment by romestylez** [comment] 2022-12-10 10:00
Will repreduce this its easy when you call like opkg update you see that. Give me a few minutes

**Comment by romestylez** [comment] 2022-12-10 10:17
Okay seems like the problem is fixxed now. Was there a update last night or something ? I install them every night so seems to be fixxed with one of the last updates.

Will try on an receiver which doesnt update every day.

**Comment by jbleyel** [comment] 2022-12-10 11:43
I will leave this issue open and you should monitor this.

**Comment by romestylez** [comment] 2022-12-10 11:44
Thanks ! I tried it on all of my openATV 7 receivers and this issue isnt present anymore. I guess it was fixxed :)

**Comment by jbleyel** [comment] 2023-04-25 05:03
Can we close this?

**Comment by romestylez** [comment] 2023-04-25 05:24
Yes for me this is fixxed since a long time

**Closed** 2023-04-25 05:59 UTC
Labels: BUG 🐞, Monitor
