### ISSUE TITLE
Skin Selection - doesn't fallaback to setup

### ISSUE THREAD

**Issue by kiddac** [openatv/enigma2#3407] opened 2024-08-25 19:12 UTC
Since you have changed the name of this. It no longer falls back to setup screen, breaking peoples skins. 
Yet if I create the screen, but miss out mandatory items it does fallback to setup screen,
Also remove all the code for mandatory fields. Nothing is mandatory, its up to the skinner what elements they put in skins. 
We just end up putting in a load of junk code that say position="0,0" size="0,0".
And if your code breaks because you think its mandatory then you need to fix your code. Not break other peoples work

**Comment by jbleyel** [comment] 2024-08-25 19:47
If you do not have "SkinSelection" in your skin you get it from the default skin.

```
	<screen name="SkinSelection" position="center,center" size="560,600">
		<panel name="Setup"/>
		<widget name="preview" position="117,0" size="280,210" alphatest="on" zPosition="0"/>
	</screen>

```

This screen looks not good and should be fixed.

**Comment by jbleyel** [comment] 2024-08-25 19:50
The problem is that this panel -> `<panel name="Setup"/>` comes from your skin.
We may need to do that differently.

**Comment by jbleyel** [comment] 2024-08-27 18:57
https://github.com/openatv/oe-alliance-e2-skindefault/commit/0e795dcc84916b32a5caa6b84d70212db9d0bfd6

**Closed by jbleyel** 2024-08-27 18:57 UTC
Labels: BUG 🐞
